<?php

namespace ContainerA3Ngqwi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JVIJtSFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jVIJtSF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jVIJtSF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'createdAt' => ['privates', '.errored..service_locator.jVIJtSF.DateTime', NULL, 'Cannot autowire service ".service_locator.jVIJtSF": it references class "DateTime" but no such service exists.'],
        ], [
            'createdAt' => 'DateTime',
        ]);
    }
}
