<?php

namespace ContainerA3Ngqwi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Dukecity\CommandSchedulerBundle\Controller\ApiController' shared autowired service.
     *
     * @return \Dukecity\CommandSchedulerBundle\Controller\ApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/dukecity/command-scheduler-bundle/Controller/AbstractBaseController.php';
        include_once \dirname(__DIR__, 4).'/vendor/dukecity/command-scheduler-bundle/Controller/ApiController.php';

        $container->services['Dukecity\\CommandSchedulerBundle\\Controller\\ApiController'] = $instance = new \Dukecity\CommandSchedulerBundle\Controller\ApiController();

        $instance->setManagerName('default');
        $instance->setTranslator(($container->services['translator'] ?? $container->getTranslatorService()));
        $instance->setLockTimeout(false);
        $instance->setLogger(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));
        $instance->setCommandParser(($container->privates['Dukecity\\CommandSchedulerBundle\\Service\\CommandParser'] ?? $container->load('getCommandParserService')));
        $instance->setContainer($container);

        return $instance;
    }
}
