<?php

namespace ContainerA3Ngqwi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Dukecity\CommandSchedulerBundle\Command\AddCommand' shared service.
     *
     * @return \Dukecity\CommandSchedulerBundle\Command\AddCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/dukecity/command-scheduler-bundle/Command/AddCommand.php';

        $container->privates['Dukecity\\CommandSchedulerBundle\\Command\\AddCommand'] = $instance = new \Dukecity\CommandSchedulerBundle\Command\AddCommand(($container->services['doctrine'] ?? $container->getDoctrineService()), 'default');

        $instance->setName('scheduler:add');
        $instance->setDescription('Add a scheduled command');

        return $instance;
    }
}
