<?php

namespace ContainerA3Ngqwi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetailControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Dukecity\CommandSchedulerBundle\Controller\DetailController' shared autowired service.
     *
     * @return \Dukecity\CommandSchedulerBundle\Controller\DetailController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/dukecity/command-scheduler-bundle/Controller/AbstractBaseController.php';
        include_once \dirname(__DIR__, 4).'/vendor/dukecity/command-scheduler-bundle/Controller/DetailController.php';

        $container->services['Dukecity\\CommandSchedulerBundle\\Controller\\DetailController'] = $instance = new \Dukecity\CommandSchedulerBundle\Controller\DetailController();

        $instance->setManagerName('default');
        $instance->setTranslator(($container->services['translator'] ?? $container->getTranslatorService()));
        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Dukecity\\CommandSchedulerBundle\\Controller\\DetailController', $container));

        return $instance;
    }
}
