<?php

namespace ContainerA3Ngqwi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemoveCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Dukecity\CommandSchedulerBundle\Command\RemoveCommand' shared service.
     *
     * @return \Dukecity\CommandSchedulerBundle\Command\RemoveCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/dukecity/command-scheduler-bundle/Command/RemoveCommand.php';

        $container->privates['Dukecity\\CommandSchedulerBundle\\Command\\RemoveCommand'] = $instance = new \Dukecity\CommandSchedulerBundle\Command\RemoveCommand(($container->services['doctrine'] ?? $container->getDoctrineService()), 'default');

        $instance->setName('scheduler:remove');
        $instance->setAliases([0 => 'scheduler:delete']);
        $instance->setDescription('Remove a scheduled command');

        return $instance;
    }
}
