<?php

namespace ContainerUCc2Q4N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__ServiceLocator_JVIJtSF_DateTimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jVIJtSF.DateTime' shared service.
     *
     * @return \DateTime
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.jVIJtSF": it references class "DateTime" but no such service exists.');
    }
}
