<?php

namespace ContainerUCc2Q4N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VocWbTpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VocWbTp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VocWbTp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'conference' => ['privates', '.errored..service_locator.VocWbTp.App\\Entity\\Conference', NULL, 'Cannot autowire service ".service_locator.VocWbTp": it references class "App\\Entity\\Conference" but no such service exists.'],
            'conferenceRepository' => ['privates', 'App\\Repository\\ConferenceRepository', 'getConferenceRepositoryService', false],
        ], [
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'conference' => 'App\\Entity\\Conference',
            'conferenceRepository' => 'App\\Repository\\ConferenceRepository',
        ]);
    }
}
