<?php

namespace ContainerUCc2Q4N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lwh3nbSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lwh3nbS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lwh3nbS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'conferenceRepository' => ['privates', 'App\\Repository\\ConferenceRepository', 'getConferenceRepositoryService', false],
        ], [
            'conferenceRepository' => 'App\\Repository\\ConferenceRepository',
        ]);
    }
}
