<?php

namespace ContainerUCc2Q4N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConferenceControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ConferenceController' shared autowired service.
     *
     * @return \App\Controller\ConferenceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ConferenceController.php';

        $container->services['App\\Controller\\ConferenceController'] = $instance = new \App\Controller\ConferenceController(($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setContainer(($container->privates['.service_locator.JC.qEFX'] ?? $container->load('get_ServiceLocator_JC_QEFXService'))->withContext('App\\Controller\\ConferenceController', $container));

        return $instance;
    }
}
