<?php

namespace ContainerUCc2Q4N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Dukecity\CommandSchedulerBundle\Command\ListCommand' shared service.
     *
     * @return \Dukecity\CommandSchedulerBundle\Command\ListCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/dukecity/command-scheduler-bundle/Command/ListCommand.php';

        $container->privates['Dukecity\\CommandSchedulerBundle\\Command\\ListCommand'] = $instance = new \Dukecity\CommandSchedulerBundle\Command\ListCommand(($container->services['doctrine'] ?? $container->getDoctrineService()), 'default');

        $instance->setName('scheduler:list');
        $instance->setDescription('List scheduled commands');

        return $instance;
    }
}
