<?php

namespace ContainerUCc2Q4N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStartSchedulerCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Dukecity\CommandSchedulerBundle\Command\StartSchedulerCommand' shared service.
     *
     * @return \Dukecity\CommandSchedulerBundle\Command\StartSchedulerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/dukecity/command-scheduler-bundle/Command/StartSchedulerCommand.php';

        $container->privates['Dukecity\\CommandSchedulerBundle\\Command\\StartSchedulerCommand'] = $instance = new \Dukecity\CommandSchedulerBundle\Command\StartSchedulerCommand();

        $instance->setName('scheduler:start');
        $instance->setDescription('Starts command scheduler');

        return $instance;
    }
}
