<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM5xZTxN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM5xZTxN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM5xZTxN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM5xZTxN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM5xZTxN\App_KernelDevDebugContainer([
    'container.build_hash' => 'M5xZTxN',
    'container.build_id' => 'c8f99da2',
    'container.build_time' => 1649159912,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM5xZTxN');
