<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0QOBRuZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0QOBRuZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0QOBRuZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0QOBRuZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0QOBRuZ\App_KernelDevDebugContainer([
    'container.build_hash' => '0QOBRuZ',
    'container.build_id' => '84e8f547',
    'container.build_time' => 1649337964,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0QOBRuZ');
