<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6zcuavo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6zcuavo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6zcuavo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6zcuavo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6zcuavo\App_KernelDevDebugContainer([
    'container.build_hash' => '6zcuavo',
    'container.build_id' => '1b458889',
    'container.build_time' => 1649255556,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6zcuavo');
